version: '3.6'
services:
  
  nginx:
    image: linuxserver/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/bot.conf:/config/nginx/site-confs/default
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=${EMAIL}
      - URL=${URL}
      - SUBDOMAINS=www
      - TZ=Europe/London
      - VALIDATION=http
    restart: always

  feedbot:
    image: feedbot
    build: ./bot
    ports:
      - 5001:5001
    environment:
      - TG_API_KEY=${TG_API_KEY}
      - URL_PATH=${URL_PATH}
      - URL_HOSTNAME=${URL_HOSTNAME}
      - MANAGER_ID=${MANAGER_ID}
      - ADMIN_ID=${ADMIN_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - nginx
      - postgres
    restart: always

  feedmanager:
    stdin_open: true
    tty: true
    image: feedmanager
    build: ./manager
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BOT_ID=${BOT_ID}
      - ADMIN_ID=${ADMIN_ID}
    volumes:
      - ./manager/session:/usr/src/manager/session
    depends_on:
      - nginx
      - postgres

  postgres:    
    restart: always    
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}      
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}      
      - POSTGRES_DB=${POSTGRES_DB}    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   
    ports:      
      - "5432:5432"
    depends_on:
      - nginx
